import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import LayoutWrapper from "../components/LayoutWrapper";
// 1. Yahan AuthProvider import karo (Path apne folder ke hisaab se check kar lena)
import { AuthProvider } from "../context/auth-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 2. Poori app ko AuthProvider ke andar WRAP kar do */}
        <AuthProvider>
          <LayoutWrapper>{children}</LayoutWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
